frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "themes/stock-sheet/**"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "gradle/**"
          - "build.gradle.kts"

ops:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "lefthook.yml"
