spring:
  application:
    name: stock-sheet

  datasource:
    url: jdbc:postgresql://localhost:5432/stock-db
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

fmp:
  api:
    key: ${FMP_API_KEY}
    base-url: "https://financialmodelingprep.com/stable"