/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppPortfolioRouteImport } from './routes/_app/_portfolio'
import { Route as AppPortfolioIndexRouteImport } from './routes/_app/_portfolio/index'
import { Route as AppPortfolioCreatePortfolioIndexRouteImport } from './routes/_app/_portfolio/create-portfolio/index'
import { Route as AppPortfolioWalletStructureIndexRouteImport } from './routes/_app/_portfolio/wallet/structure/index'
import { Route as AppPortfolioOperationsImportIndexRouteImport } from './routes/_app/_portfolio/operations/import/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/_portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioIndexRoute = AppPortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPortfolioRoute,
} as any)
const AppPortfolioCreatePortfolioIndexRoute =
  AppPortfolioCreatePortfolioIndexRouteImport.update({
    id: '/create-portfolio/',
    path: '/create-portfolio/',
    getParentRoute: () => AppPortfolioRoute,
  } as any)
const AppPortfolioWalletStructureIndexRoute =
  AppPortfolioWalletStructureIndexRouteImport.update({
    id: '/wallet/structure/',
    path: '/wallet/structure/',
    getParentRoute: () => AppPortfolioRoute,
  } as any)
const AppPortfolioOperationsImportIndexRoute =
  AppPortfolioOperationsImportIndexRouteImport.update({
    id: '/operations/import/',
    path: '/operations/import/',
    getParentRoute: () => AppPortfolioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppPortfolioIndexRoute
  '/create-portfolio': typeof AppPortfolioCreatePortfolioIndexRoute
  '/operations/import': typeof AppPortfolioOperationsImportIndexRoute
  '/wallet/structure': typeof AppPortfolioWalletStructureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppPortfolioIndexRoute
  '/create-portfolio': typeof AppPortfolioCreatePortfolioIndexRoute
  '/operations/import': typeof AppPortfolioOperationsImportIndexRoute
  '/wallet/structure': typeof AppPortfolioWalletStructureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_portfolio': typeof AppPortfolioRouteWithChildren
  '/_app/_portfolio/': typeof AppPortfolioIndexRoute
  '/_app/_portfolio/create-portfolio/': typeof AppPortfolioCreatePortfolioIndexRoute
  '/_app/_portfolio/operations/import/': typeof AppPortfolioOperationsImportIndexRoute
  '/_app/_portfolio/wallet/structure/': typeof AppPortfolioWalletStructureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-portfolio'
    | '/operations/import'
    | '/wallet/structure'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-portfolio' | '/operations/import' | '/wallet/structure'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_portfolio'
    | '/_app/_portfolio/'
    | '/_app/_portfolio/create-portfolio/'
    | '/_app/_portfolio/operations/import/'
    | '/_app/_portfolio/wallet/structure/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_portfolio': {
      id: '/_app/_portfolio'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_portfolio/': {
      id: '/_app/_portfolio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppPortfolioIndexRouteImport
      parentRoute: typeof AppPortfolioRoute
    }
    '/_app/_portfolio/create-portfolio/': {
      id: '/_app/_portfolio/create-portfolio/'
      path: '/create-portfolio'
      fullPath: '/create-portfolio'
      preLoaderRoute: typeof AppPortfolioCreatePortfolioIndexRouteImport
      parentRoute: typeof AppPortfolioRoute
    }
    '/_app/_portfolio/wallet/structure/': {
      id: '/_app/_portfolio/wallet/structure/'
      path: '/wallet/structure'
      fullPath: '/wallet/structure'
      preLoaderRoute: typeof AppPortfolioWalletStructureIndexRouteImport
      parentRoute: typeof AppPortfolioRoute
    }
    '/_app/_portfolio/operations/import/': {
      id: '/_app/_portfolio/operations/import/'
      path: '/operations/import'
      fullPath: '/operations/import'
      preLoaderRoute: typeof AppPortfolioOperationsImportIndexRouteImport
      parentRoute: typeof AppPortfolioRoute
    }
  }
}

interface AppPortfolioRouteChildren {
  AppPortfolioIndexRoute: typeof AppPortfolioIndexRoute
  AppPortfolioCreatePortfolioIndexRoute: typeof AppPortfolioCreatePortfolioIndexRoute
  AppPortfolioOperationsImportIndexRoute: typeof AppPortfolioOperationsImportIndexRoute
  AppPortfolioWalletStructureIndexRoute: typeof AppPortfolioWalletStructureIndexRoute
}

const AppPortfolioRouteChildren: AppPortfolioRouteChildren = {
  AppPortfolioIndexRoute: AppPortfolioIndexRoute,
  AppPortfolioCreatePortfolioIndexRoute: AppPortfolioCreatePortfolioIndexRoute,
  AppPortfolioOperationsImportIndexRoute:
    AppPortfolioOperationsImportIndexRoute,
  AppPortfolioWalletStructureIndexRoute: AppPortfolioWalletStructureIndexRoute,
}

const AppPortfolioRouteWithChildren = AppPortfolioRoute._addFileChildren(
  AppPortfolioRouteChildren,
)

interface AppRouteChildren {
  AppPortfolioRoute: typeof AppPortfolioRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppPortfolioRoute: AppPortfolioRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
