/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletStructureIndexRouteImport } from './routes/wallet/structure/index'
import { Route as OperationsImportIndexRouteImport } from './routes/operations/import/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletStructureIndexRoute = WalletStructureIndexRouteImport.update({
  id: '/wallet/structure/',
  path: '/wallet/structure/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsImportIndexRoute = OperationsImportIndexRouteImport.update({
  id: '/operations/import/',
  path: '/operations/import/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/operations/import': typeof OperationsImportIndexRoute
  '/wallet/structure': typeof WalletStructureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/operations/import': typeof OperationsImportIndexRoute
  '/wallet/structure': typeof WalletStructureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/operations/import/': typeof OperationsImportIndexRoute
  '/wallet/structure/': typeof WalletStructureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/operations/import' | '/wallet/structure'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/operations/import' | '/wallet/structure'
  id: '__root__' | '/' | '/operations/import/' | '/wallet/structure/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OperationsImportIndexRoute: typeof OperationsImportIndexRoute
  WalletStructureIndexRoute: typeof WalletStructureIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/structure/': {
      id: '/wallet/structure/'
      path: '/wallet/structure'
      fullPath: '/wallet/structure'
      preLoaderRoute: typeof WalletStructureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/import/': {
      id: '/operations/import/'
      path: '/operations/import'
      fullPath: '/operations/import'
      preLoaderRoute: typeof OperationsImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OperationsImportIndexRoute: OperationsImportIndexRoute,
  WalletStructureIndexRoute: WalletStructureIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
