CREATE TABLE operations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id      VARCHAR(255)                            NOT NULL,
    stock_symbol     VARCHAR(255)                            NOT NULL,
    type             VARCHAR(255)                            NOT NULL,
    volume           DECIMAL                                 NOT NULL,
    open_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    price_per_volume DECIMAL                                 NOT NULL,
    total_price      DECIMAL                                 NOT NULL,
    currency         VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_operations PRIMARY KEY (id)
);