CREATE TABLE portfolio
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    currency VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_portfolio PRIMARY KEY (id)
);

ALTER TABLE operations
    ADD portfolio_id BIGINT;

ALTER TABLE operations
    ALTER COLUMN portfolio_id SET NOT NULL;

ALTER TABLE operations
    ADD CONSTRAINT FK_OPERATIONS_ON_PORTFOLIO FOREIGN KEY (portfolio_id) REFERENCES portfolio (id);

ALTER TABLE operations
DROP
COLUMN currency;