CREATE TABLE stocks
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    symbol   VARCHAR(255)                            NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    exchange VARCHAR(255)                            NOT NULL,
    industry VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_stocks PRIMARY KEY (id)
);

ALTER TABLE operations
    ADD stock_id BIGINT;

ALTER TABLE operations
    ALTER COLUMN stock_id SET NOT NULL;

ALTER TABLE stocks
    ADD CONSTRAINT uc_stocks_symbol UNIQUE (symbol);

ALTER TABLE operations
    ADD CONSTRAINT FK_OPERATIONS_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stocks (id);

ALTER TABLE operations
DROP COLUMN stock_symbol;