CREATE TABLE stock_entity
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    symbol   VARCHAR(255)                            NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    exchange VARCHAR(255)                            NOT NULL,
    industry VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_stockentity PRIMARY KEY (id)
);

ALTER TABLE operations
    ADD stock_id BIGINT;

ALTER TABLE operations
    ALTER COLUMN stock_id SET NOT NULL;

ALTER TABLE stock_entity
    ADD CONSTRAINT uc_stockentity_symbol UNIQUE (symbol);

ALTER TABLE operations
    ADD CONSTRAINT FK_OPERATIONS_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stock_entity (id);

ALTER TABLE operations
DROP
COLUMN stock_symbol;