CREATE TABLE stocks_quotes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    closed_price DECIMAL                                 NOT NULL,
    date         date                                    NOT NULL,
    stock_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_stocks_quotes PRIMARY KEY (id)
);

ALTER TABLE stocks_quotes
    ADD CONSTRAINT uk_stock_quote_date_id UNIQUE (date, stock_id);

ALTER TABLE stocks_quotes
    ADD CONSTRAINT FK_STOCKS_QUOTES_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stocks (id);